name: Workflow Name
run-name: ${{ github.actor }}

on:
    pull_request:
        branches: [main]

jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: echo "step 1"
            - name: PR step 2
              run: |
                echo "base_ref=${GITHUB_BASE_REF} head_ref=${GITHUB_HEAD_REF}"
              if: github.event_name == 'pull_request'
            - name: Push step 2
              run: |
                echo "ref=${GITHUB_REF}"